import { describe, expect, it } from 'vitest';
import { PHYSICS } from '../src/config/physics';
import { assessLanding, captureFuelTelemetry, captureTouchdown, classifyLanding, initialCraft, stepPhysics, thrustVector } from '../src/physics/engine';
import { Mission } from '../src/simulation/mission';

describe('lunar physics', () => {
  it('accelerates downward under lunar gravity without thrust', () => { const next = stepPhysics(initialCraft(), 1); expect(next.velocity.y).toBeCloseTo(-6.62, 2); });
  it('consumes fuel while the engine is active', () => { const craft = { ...initialCraft(), engineOn: true, throttle: 1 }; const next = stepPhysics(craft, 2); expect(next.fuel).toBeLessThan(craft.fuel); });
  it('cuts the engine when fuel is exhausted', () => { const craft = { ...initialCraft(), fuel: 0.01, engineOn: true, throttle: 1 }; const next = stepPhysics(craft, 1); expect(next.fuel).toBe(0); expect(next.engineOn).toBe(false); });
  it('changes horizontal trajectory when tilted', () => { const craft = { ...initialCraft(), angle: Math.PI / 6, engineOn: true, throttle: 1 }; expect(stepPhysics(craft, 1).velocity.x).toBeGreaterThan(0); });
  it('can overcome lunar gravity and brake a vertical descent', () => { const craft = { ...initialCraft(), velocity: { x: 0, y: -10 }, engineOn: true, throttle: 1 }; const next = stepPhysics(craft, 1); expect(thrustVector(craft).y).toBeGreaterThan(0); expect(next.velocity.y).toBeGreaterThan(craft.velocity.y); });
  it('loses vertical authority when tilted because thrust is redirected', () => { const upright = { ...initialCraft(), engineOn: true, throttle: 1 }; const tilted = { ...upright, angle: Math.PI / 3 }; expect(thrustVector(upright).y).toBeGreaterThan(thrustVector(tilted).y); expect(Math.abs(thrustVector(tilted).x)).toBeGreaterThan(0); });
  it('is stable across frame rates through fixed steps', () => { let a = initialCraft(); let b = initialCraft(); for (let i = 0; i < 60; i++) a = stepPhysics(a, 1 / 60); for (let i = 0; i < 30; i++) b = stepPhysics(b, 1 / 30); expect(a.position.y).toBeCloseTo(b.position.y, 1); });
  it('classifies safe, hard and catastrophic landings', () => { expect(classifyLanding({ ...initialCraft(), velocity: { x: 1, y: -1 }, angle: 0 })).toBe('success'); expect(classifyLanding({ ...initialCraft(), velocity: { x: 3, y: -4 }, angle: 0 })).toBe('hard'); expect(classifyLanding({ ...initialCraft(), velocity: { x: 0, y: -20 }, angle: 0 })).toBe('crash'); });
  it('never leaves craft below terrain after contact resolution', () => { const craft = { ...initialCraft(), position: { x: 0, y: -10 } }; expect((craft.position.y <= PHYSICS.terrainBase)).toBe(true); });
  it('preserves interpolated touchdown speed before contact resolution', () => { const before = { ...initialCraft(), position: { x: 4, y: 0.05 }, velocity: { x: 2, y: -1.2 }, fuel: 4000 }; const after = { ...before, position: { x: 4.02, y: -0.05 }, velocity: { x: 2.2, y: -1.4 }, fuel: 3999 }; const touchdown = captureTouchdown(before, after, 101, 0.1); expect(touchdown.verticalSpeed).toBeCloseTo(-1.3, 5); expect(touchdown.horizontalSpeed).toBeCloseTo(2.1, 5); expect(touchdown.flightTime).toBeCloseTo(101.05, 5); expect(touchdown.position.y).toBe(0); });
  it('grades a very soft upright touchdown A+', () => { const assessment = assessLanding({ verticalSpeed: -0.4, horizontalSpeed: 0.3, totalSpeed: 0.5, angle: 0.02, fuel: 3000, mass: 13000, flightTime: 10, position: { x: 0, y: 0 } }); expect(assessment.grade).toBe('A+'); expect(assessment.safetyGrade).toBe('A+'); expect(assessment.condition).toBe('Intact'); });
  it('uses all touchdown axes and does not grade a hard landing A+', () => { const assessment = assessLanding({ verticalSpeed: -2, horizontalSpeed: 4, totalSpeed: 4.47, angle: 0, fuel: 3000, mass: 13000, flightTime: 10, position: { x: 0, y: 0 } }); expect(assessment.grade).toBe('B'); expect(assessment.safetyGrade).toBe('B'); expect(assessment.grade).not.toBe('A+'); });
  it('classifies a critical and a crash touchdown', () => { expect(assessLanding({ verticalSpeed: -8, horizontalSpeed: 7, totalSpeed: 10.63, angle: 0.4, fuel: 1000, mass: 11100, flightTime: 10, position: { x: 0, y: 0 } }).grade).toBe('C'); expect(assessLanding({ verticalSpeed: -20, horizontalSpeed: 0, totalSpeed: 20, angle: 0, fuel: 0, mass: 10100, flightTime: 10, position: { x: 0, y: 0 } }).grade).toBe('F'); });
  it('stores one touchdown result and clears it on reset', () => { const mission = new Mission(); mission.state = { ...mission.state, status: 'active', craft: { ...initialCraft(), position: { x: 0, y: 0.01 }, velocity: { x: 0, y: -1.2 } } }; mission.tick(PHYSICS.fixedStep); expect(mission.state.touchdown?.verticalSpeed).toBeLessThan(0); const first = mission.state.touchdown; mission.tick(1); expect(mission.state.touchdown).toBe(first); mission.reset(); expect(mission.state.touchdown).toBeUndefined(); expect(mission.state.assessment).toBeUndefined(); });
  it('returns deterministic results for identical touchdown inputs', () => { const input = { verticalSpeed: -1.2, horizontalSpeed: 0.8, totalSpeed: 1.44, angle: 0.03, fuel: 2000, mass: 12100, flightTime: 42, position: { x: 12, y: 0 } }; expect(assessLanding(input)).toEqual(assessLanding({ ...input, position: { ...input.position } })); });
  it('calculates fuel used from the configured starting reserve', () => { const fuel = captureFuelTelemetry(PHYSICS.initialFuel, 6150, true); expect(fuel.initialFuel).toBe(8200); expect(fuel.remainingFuel).toBe(6150); expect(fuel.fuelUsed).toBe(2050); expect(fuel.fuelUsedPercent).toBeCloseTo(25, 5); expect(fuel.efficiencyGrade).toBe('A'); });
  it('does not reward fuel economy for unsafe landings', () => { expect(captureFuelTelemetry(PHYSICS.initialFuel, 8000, false).efficiencyGrade).toBe('N/A'); expect(captureFuelTelemetry(PHYSICS.initialFuel, 0, true).efficiencyGrade).toBe('D'); });
  it('resets fuel telemetry for a new launch', () => { const mission = new Mission(); mission.start(); mission.state.fuelTelemetry = captureFuelTelemetry(mission.state.initialFuel!, 7000, true); mission.reset(); expect(mission.state.initialFuel).toBeUndefined(); expect(mission.state.fuelTelemetry).toBeUndefined(); mission.start(); expect(mission.state.initialFuel).toBe(PHYSICS.initialFuel); });
  it('keeps Mission results independent of render FPS', () => { const a = new Mission(); const b = new Mission(); a.start(); b.start(); for (let i = 0; i < 60; i++) a.tick(1 / 60); for (let i = 0; i < 30; i++) b.tick(1 / 30); expect(a.state.time).toBeCloseTo(b.state.time, 8); expect(a.state.craft.position.y).toBeCloseTo(b.state.craft.position.y, 8); });
  it('uses documented engineering engine limits while keeping Classic unchanged', () => { const engineering = new Mission('engineering'); expect(engineering.config.maxThrust).toBe(44482); expect(engineering.config.initialFuel).toBe(730); engineering.setThrottle(1); engineering.start(); const next = stepPhysics(engineering.state.craft, engineering.config.fixedStep, engineering.config); expect(next.fuel).toBeLessThan(730); const classic = new Mission('classic'); expect(classic.config.maxThrust).toBe(PHYSICS.maxThrust); expect(classic.config.initialFuel).toBe(PHYSICS.initialFuel); });
  it('captures interpolated touchdown mass and never grades fuel savings above safety', () => { const before = { ...initialCraft(), position: { x: 0, y: 0.1 }, fuel: 4000, mass: 14100 }; const after = { ...before, position: { x: 0, y: -0.1 }, fuel: 3998, mass: 14098 }; const touchdown = captureTouchdown(before, after, 5, 0.1); expect(touchdown.mass).toBeCloseTo(14099, 8); expect(captureFuelTelemetry(8200, 8100, false).efficiencyGrade).toBe('N/A'); });
});
